export const transactions = [
    {
      transaction_id: "1",
      transaction_date: "2019-01-01",
      transaction_amount: 100.0,
      transaction_type: "debit",
      transaction_description: "Payment for groceries",
      merchant_name: "SuperMart",
      card_type: "Visa",
    },
    {
      transaction_id: "2",
      transaction_date: "2019-01-02",
      transaction_amount: 50.0,
      transaction_type: "credit",
      transaction_description: "Refund for returned item",
      merchant_name: "OnlineShop",
      card_type: "MasterCard",
    },
    {
      transaction_id: "3",
      transaction_date: "2019-01-03",
      transaction_amount: 75.0,
      transaction_type: "debit",
      transaction_description: "Dinner with friends",
      merchant_name: "RestaurantABC",
      card_type: "Amex",
    },
    {
      transaction_id: "4",
      transaction_date: "2019-01-04",
      transaction_amount: 120.0,
      transaction_type: "debit",
      transaction_description: "Shopping at Mall",
      merchant_name: "FashionStoreXYZ",
      card_type: "Discover",
    },
    {
      transaction_id: "5",
      transaction_date: "2019-01-05",
      transaction_amount: 25.0,
      transaction_type: "credit",
      transaction_description: "Returned defective product",
      merchant_name: "ElectronicsShop",
      card_type: "Visa",
    },
    {
      transaction_id: "6",
      transaction_date: "2019-01-06",
      transaction_amount: 60.0,
      transaction_type: "debit",
      transaction_description: "Gasoline refill",
      merchant_name: "GasStationXYZ",
      card_type: "MasterCard",
    },
    {
      transaction_id: "7",
      transaction_date: "2019-01-07",
      transaction_amount: 40.0,
      transaction_type: "debit",
      transaction_description: "Lunch with colleagues",
      merchant_name: "Cafe123",
      card_type: "Visa",
    },
    {
      transaction_id: "8",
      transaction_date: "2019-01-08",
      transaction_amount: 90.0,
      transaction_type: "credit",
      transaction_description: "Movie tickets",
      merchant_name: "CinemaXYZ",
      card_type: "Amex",
    },
    {
      transaction_id: "9",
      transaction_date: "2019-01-09",
      transaction_amount: 150.0,
      transaction_type: "debit",
      transaction_description: "Weekend getaway",
      merchant_name: "ResortABC",
      card_type: "Discover",
    },
    {
      transaction_id: "10",
      transaction_date: "2019-01-10",
      transaction_amount: 20.0,
      transaction_type: "credit",
      transaction_description: "Cashback reward",
      merchant_name: "BankXYZ",
      card_type: "Visa",
    },
    {
      transaction_id: "11",
      transaction_date: "2019-01-11",
      transaction_amount: 65.0,
      transaction_type: "debit",
      transaction_description: "Dinner with family",
      merchant_name: "FamilyRestaurant",
      card_type: "MasterCard",
    },
    {
      transaction_id: "12",
      transaction_date: "2019-01-12",
      transaction_amount: 30.0,
      transaction_type: "credit",
      transaction_description: "Returned books",
      merchant_name: "BookstoreABC",
      card_type: "Visa",
    },
    {
      transaction_id: "13",
      transaction_date: "2019-01-13",
      transaction_amount: 85.0,
      transaction_type: "debit",
      transaction_description: "Home appliances purchase",
      merchant_name: "ApplianceStoreXYZ",
      card_type: "Discover",
    },
    {
      transaction_id: "14",
      transaction_date: "2019-01-14",
      transaction_amount: 45.0,
      transaction_type: "debit",
      transaction_description: "Coffee and snacks",
      merchant_name: "CoffeeShop123",
      card_type: "Amex",
    },
    {
      transaction_id: "15",
      transaction_date: "2019-01-15",
      transaction_amount: 110.0,
      transaction_type: "credit",
      transaction_description: "Electronics purchase",
      merchant_name: "ElectronicsStoreXYZ",
      card_type: "MasterCard",
    },
    {
      transaction_id: "16",
      transaction_date: "2019-01-16",
      transaction_amount: 70.0,
      transaction_type: "debit",
      transaction_description: "Car maintenance",
      merchant_name: "AutoServiceABC",
      card_type: "Visa",
    },
    {
      transaction_id: "17",
      transaction_date: "2019-01-17",
      transaction_amount: 55.0,
      transaction_type: "credit",
      transaction_description: "Refund for damaged item",
      merchant_name: "OnlineStoreXYZ",
      card_type: "Discover",
    },
    {
      transaction_id: "18",
      transaction_date: "2019-01-18",
      transaction_amount: 80.0,
      transaction_type: "debit",
      transaction_description: "Dinner at fancy restaurant",
      merchant_name: "FineDiningXYZ",
      card_type: "Amex",
    },
    {
      transaction_id: "19",
      transaction_date: "2019-01-19",
      transaction_amount: 95.0,
      transaction_type: "credit",
      transaction_description: "Grocery shopping",
      merchant_name: "GroceryStore123",
      card_type: "MasterCard",
    },
    {
      transaction_id: "20",
      transaction_date: "2019-01-20",
      transaction_amount: 35.0,
      transaction_type: "credit",
      transaction_description: "Cashback reward",
      merchant_name: "BankXYZ",
      card_type: "Visa",
    },
    {
      transaction_id: "21",
      transaction_date: "2019-01-21",
      transaction_amount: 130.0,
      transaction_type: "credit",
      transaction_description: "Shopping spree",
      merchant_name: "MallABC",
      card_type: "Discover",
    },
  ];
